// Generated by `make fingerprints` (scripts/fingerprints.ts) against a live
// tenant; do not edit by hand. A fingerprint is a hash of the page's
// tag/id/class skeleton (no text, no data), see inspectPage().
import type { PageKey } from "./pages.js";

export const FINGERPRINTS: Partial<Record<PageKey, { fingerprint: string; recordedAt: string }>> = {
  contacts: { fingerprint: "39e7fa4d", recordedAt: "2026-09-06" },
  subjects: { fingerprint: "007e1b88", recordedAt: "2026-09-06" },
  bookings: { fingerprint: "e1c6f6e8", recordedAt: "2026-09-06" },
  files: { fingerprint: "3a26642d", recordedAt: "2026-09-06" },
  grades: { fingerprint: "8d1261cb", recordedAt: "2026-09-06" },
  documents: { fingerprint: "a0f5022f", recordedAt: "2026-09-06" },
  unreportedAbsence: { fingerprint: "c7f6dd6d", recordedAt: "2026-09-06" },
  attendanceReport: { fingerprint: "6713a98a", recordedAt: "2026-09-06" },
  assessmentCriteria: { fingerprint: "9de595ed", recordedAt: "2026-09-06" },
};
