/**
 * Record the structural fingerprint of every browser-read page against the
 * configured (live) tenant and write src/core/portal/fingerprints.ts.
 * Local only: needs a session (`make login`) and, for gated pages, a web
 * session (`make login-web`). Pages that cannot be reached keep their old
 * fingerprint. Nothing but tag/id/class skeletons is read.
 */
import { writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { loadContext } from "../src/shared/bootstrap.js";
import {
  createApiPortal,
  createBrowserSession,
  verifyPages,
  FINGERPRINTS,
  PAGE_KEYS,
} from "../src/core/index.js";

const ctx = loadContext({ env: process.env, home: homedir(), platform: process.platform })();
await ctx.manager.ensureSession();
const session = createBrowserSession(ctx.manager, { engine: ctx.config.browser });
const reports = await verifyPages(session, {
  hasWebSession: ctx.manager.getWebSession() !== null,
  syncWebChild: () => createApiPortal(ctx.manager).syncWebChild(),
  fingerprints: {},
});
await session.close();
const next = { ...FINGERPRINTS };
const recordedAt = new Date().toISOString().slice(0, 10);
for (const r of reports) {
  if (r.fingerprint && r.status === "ok") next[r.page] = { fingerprint: r.fingerprint, recordedAt };
  console.log(
    `${r.page.padEnd(20)} ${r.status}${r.missing.length ? " missing " + r.missing.join(", ") : ""}${r.reason ? " " + r.reason : ""}`,
  );
}
const entries = PAGE_KEYS.filter((k) => next[k]).map((k) => `  ${k}: ${JSON.stringify(next[k])},`);
writeFileSync(
  "src/core/portal/fingerprints.ts",
  `// Generated by \`make fingerprints\` (scripts/fingerprints.ts) against a live
// tenant; do not edit by hand. A fingerprint is a hash of the page's
// tag/id/class skeleton (no text, no data), see inspectPage().
import type { PageKey } from "./pages.js";

export const FINGERPRINTS: Partial<Record<PageKey, { fingerprint: string; recordedAt: string }>> = {
${entries.join("\n")}
};
`,
);
console.log(`wrote src/core/portal/fingerprints.ts (${entries.length} pages)`);
