/**
 * Generate reference docs from the operation registry:
 *   docs/reference/tools.md                     (MCP tools)
 *   docs/reference/commands.md                  (CLI commands)
 *   skills/schoolsoft/references/commands.md    (same, for the skill)
 *   docs/reference/rest-api.md                  (the connector's REST routes and problems)
 *   docs/reference/openapi.json                 (the same routes as an OpenAPI 3.1 document)
 *   src/client/api.gen.ts                       (the typed client's schemas and types)
 * A boundary test asserts the committed files equal this output.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { z } from "zod";
import { operations } from "../src/core/index.js";
import { flagsFromSchema, kebab } from "../src/cli/flags.js";
import { textRenderer, TEXT_RENDERERS } from "../src/cli/text/registry.js";
import { TOOL_PREFIX } from "../src/mcp/server.js";
import { restRoutes } from "../src/http/routes.js";
import { PROBLEMS, PROBLEM_TYPE_PREFIX } from "../src/http/problem.js";
import { REST_REQUESTS_PER_MINUTE } from "../src/http/rest.js";
import { ConnectorChildrenSchema, SessionSchema } from "../src/http/api-schemas.js";
import { API_VERSION, RESOURCE_PATH, openApiDocument } from "../src/http/openapi.js";
import { API_BASE } from "../src/http/routes.js";
import { tsDeclaration, tsType } from "./json-schema-ts.js";
import {
  NEXT_EVENT_DAYS,
  NextEventSchema,
  OVERVIEW_QUERY,
  OVERVIEW_SCOPES,
  OVERVIEW_SLUG,
  OverviewSchema,
  SECTION_PROBLEMS,
} from "../src/http/overview.js";

const HEADER =
  "<!-- Generated by `make docs` from src/core/operations — do not edit by hand. -->\n\n";

function annotationBadges(op: (typeof operations)[number]): string {
  const a = op.annotations;
  return [
    a.readOnly ? "read-only" : "writes",
    a.destructive ? "destructive" : null,
    a.idempotent ? "idempotent" : null,
    a.requiresAuth ? "needs login" : "no login needed",
  ]
    .filter(Boolean)
    .join(", ");
}

function exampleArgs(op: (typeof operations)[number]): Record<string, unknown> {
  const ex: Record<string, unknown> = {};
  for (const s of flagsFromSchema(op.input)) {
    if (!s.required) continue;
    ex[s.key] =
      s.kind === "number"
        ? 1
        : s.kind === "boolean"
          ? true
          : s.kind === "enum"
            ? s.choices?.[0]
            : "Rösjöskolan";
  }
  if (op.name === "get_schedule") ex.week = 37;
  return ex;
}

interface JsonNode {
  type?: string | string[];
  format?: string;
  const?: unknown;
  enum?: unknown[];
  description?: string;
  anyOf?: JsonNode[];
  items?: JsonNode;
  properties?: Record<string, JsonNode>;
}

/** A JSON Schema node as a short type, e.g. `string (date-time)`, `object or null`. */
function typeName(node: JsonNode): string {
  if (node.anyOf) return node.anyOf.map(typeName).join(" or ");
  if (node.const !== undefined) return `\`${JSON.stringify(node.const)}\``;
  if (node.enum) return node.enum.map((v) => `\`${JSON.stringify(v)}\``).join(" \\| ");
  if (node.type === "array") return `${typeName(node.items!)}[]`;
  const type = Array.isArray(node.type) ? node.type.join(" or ") : node.type!;
  return node.format ? `${type} (${node.format})` : type;
}

/** One row per field, nested objects and array items flattened into dotted paths. */
function outputRows(node: JsonNode, path: string, rows: string[][]): string[][] {
  const object =
    node.type === "object"
      ? node
      : node.type === "array"
        ? node.items!.type === "object"
          ? node.items
          : undefined
        : node.anyOf?.find((n) => n.type === "object");
  for (const [key, child] of Object.entries(object?.properties ?? {})) {
    const at = path ? `${path}${node.type === "array" ? "[]" : ""}.${key}` : key;
    rows.push([`\`${at}\``, typeName(child), child.description ?? ""]);
    outputRows(child, at, rows);
  }
  return rows;
}

/** The field table of a typed operation's output schema. */
function outputTable(output: z.ZodType): string {
  const schema = z.toJSONSchema(output, { io: "output" }) as JsonNode;
  let md = "| Field | Type | Description |\n|---|---|---|\n";
  for (const row of outputRows(schema, "", [])) md += `| ${row.join(" | ")} |\n`;
  return md + "\n";
}

/** The validated result shape of a typed operation, generated from its output schema. */
export function renderOutput(op: (typeof operations)[number]): string {
  if (!op.output) return "";
  return (
    "Output (validated; a response that does not fit is a `response_drift` error, exit 7):\n\n" +
    outputTable(op.output)
  );
}

export function renderTools(): string {
  let md =
    HEADER +
    "# MCP tools\n\nServer: `schoolsoft-agent-mcp` (stdio). Every tool returns JSON as `structuredContent` plus a text copy (truncated at 25 000 characters). Tools with an Output table declare it as their `outputSchema`; their results are validated and always carry `structuredContent`, and their errors are the two text lines only.\n\n";
  md += "| Tool | Purpose | Annotations |\n|---|---|---|\n";
  for (const op of operations)
    md += `| \`${TOOL_PREFIX}${op.name}\` | ${op.title} | ${annotationBadges(op)} |\n`;
  md += "\n";
  for (const op of operations) {
    md += `## \`${TOOL_PREFIX}${op.name}\`\n\n${op.description.trim()}\n\n`;
    const specs = flagsFromSchema(op.input);
    if (specs.length) {
      md += "| Argument | Type | Required | Description |\n|---|---|---|---|\n";
      for (const s of specs)
        md += `| \`${s.key}\` | ${s.kind}${s.choices ? ` (${s.choices.join(" \\| ")})` : ""} | ${s.required ? "yes" : "no"} | ${s.description} |\n`;
      md += "\n";
    } else {
      md += "_No arguments._\n\n";
    }
    md += renderOutput(op);
    md +=
      "Example call:\n\n```json\n" +
      JSON.stringify({ name: TOOL_PREFIX + op.name, arguments: exampleArgs(op) }, null, 2) +
      "\n```\n\n";
  }
  return md;
}

export function renderCommands(): string {
  let md =
    HEADER +
    "# CLI commands\n\nBinary: `schoolsoft-agent`. Output is JSON on stdout; errors are two lines on stderr (the problem, then what to do next).\n\n";
  md +=
    "Exit codes: `0` ok · `1` bug · `2` not authenticated (run `login`) · `3` not configured (run `configure`) · `4` network · `5` not available · `6` input · `7` upstream (including `response_drift`: the portal's answer changed shape).\n\n";
  md +=
    "Global flags: `--school <slug>`, `--org-id <id>`, `--config-dir <dir>`, `--state-dir <dir>`, `--pretty`, `--format <json|text>`.\n\n";
  md +=
    "`--format json` is the default and what agents and scripts read. `--format text` prints a view for people, in Swedish or English like the error messages, for " +
    Object.keys(TEXT_RENDERERS)
      .map((name) => `\`${kebab(name)}\``)
      .join(", ") +
    "; any other command prints pretty JSON and a one-line note on stderr.\n\n";
  md += "| Command | Purpose | Annotations |\n|---|---|---|\n";
  for (const op of operations)
    md += `| \`${kebab(op.name)}\` | ${op.title} | ${annotationBadges(op)} |\n`;
  md +=
    "| `configure` | Write config.json (interactive school lookup or `--school/--org-id/--query`) | no login needed |\n";
  md +=
    "| `doctor` | Diagnose environment, config, session, connectivity (`--fix` migrates a legacy store) | no login needed |\n";
  md +=
    "| `doctor --verify` | Check that each typed read still parses against the live portal; prints statuses, never data (`--all-children` checks every child) | read-only, needs a saved session; exit 7 on drift |\n\n";
  for (const op of operations) {
    md += `## \`schoolsoft-agent ${kebab(op.name)}\`\n\n${op.description.trim()}\n\n`;
    const specs = flagsFromSchema(op.input);
    if (specs.length) {
      md += "| Flag | Required | Description |\n|---|---|---|\n";
      for (const s of specs)
        md += `| \`${s.flag}\` | ${s.required ? "yes" : "no"} | ${s.description}${s.choices ? ` (${s.choices.join(", ")})` : ""} |\n`;
      md += "\n";
    }
    md += renderOutput(op);
    if (textRenderer(op.name))
      md += "`--format text` prints a view of this result for people instead of JSON.\n\n";
    const ex = exampleArgs(op);
    const flags = Object.entries(ex)
      .map(([k, v]) =>
        typeof v === "boolean" ? `--${kebab(k)}` : `--${kebab(k)} ${JSON.stringify(v)}`,
      )
      .join(" ");
    md += "```bash\nschoolsoft-agent " + kebab(op.name) + (flags ? " " + flags : "") + "\n```\n\n";
  }
  return md;
}

const OVERVIEW_PATH = `/api/v1/children/{childId}/${OVERVIEW_SLUG}`;

/** The composite overview (E5.6): not generated from one operation, so described here. */
function renderOverview(): string {
  let md = `## \`GET ${OVERVIEW_PATH}\`\n\n`;
  md +=
    "A dashboard's first paint for one child in one request: the week's lessons and lunch and the next school event. " +
    "The sections are the operations above, read in one turn of the connector's queue (one grant check, at most one child switch upstream, the read cache as usual), so a warm overview sends nothing to the school portal. " +
    `No scope of its own: each section needs its operation's scope, and a token with none of ${OVERVIEW_SCOPES.map((s) => `\`${s}\``).join(", ")} is refused with \`403\`. ` +
    "`{childId}` is an `id` from `/children`; a child outside the connection's approval is refused with `403` before anything is read. " +
    "Design: [composite overview spec](../planning/specs/2026-09-26-composite-overview.md).\n\n";
  md += "| Query parameter | Type | Description |\n|---|---|---|\n";
  for (const q of OVERVIEW_QUERY.query) md += `| \`${q.name}\` | ${q.kind} | ${q.description} |\n`;
  md +=
    "\n**The week.** Weeks are ISO weeks named by dates in Europe/Stockholm. The school portal is asked for a week number only, so its year is the one in which that week starts nearest today; a `date` whose week is further than about half a year from today would be read for another year and is refused with `400`.\n\n";
  md += outputTable(OverviewSchema.pick({ child: true, week: true }));
  md +=
    "**Sections.** `schedule`, `lunch` and `nextEvent` are each one of:\n\n" +
    "| `status` | Other field | Meaning |\n|---|---|---|\n" +
    "| `ok` | `data` | The section's validated data |\n" +
    "| `not-granted` | `scope` | The token lacks this scope; nothing was read for the section |\n" +
    "| `error` | `problem` | The problem details body the single route would have answered (see [Problems](#problems)), in the negotiated language |\n\n" +
    "| Section | Operation | `data` |\n|---|---|---|\n" +
    "| `schedule` | `get_schedule` for the week | as `GET /api/v1/children/{childId}/schedule` answers it |\n" +
    "| `lunch` | `get_lunch_menu` for the week | as `GET /api/v1/children/{childId}/lunch-menu` answers it |\n" +
    `| \`nextEvent\` | \`get_calendar\` from today, ${NEXT_EVENT_DAYS} days | below |\n\n`;
  md += outputTable(NextEventSchema);
  md +=
    `**Partial failure.** A section keeps its own failure when it concerns that read (${[...SECTION_PROBLEMS].map((p) => `\`${p}\``).join(", ")}); the others are still served and the status is \`200\`. ` +
    "When the school portal pushes back on one section, the request budget refuses the remaining ones without sending them, and they say `portal-pushback` with `retryAt`. " +
    "Everything about the request as a whole fails it with the single routes' status and releases no section: the token or grant (`401`), the child (`403`), the connector's SchoolSoft session (`409`), a busy connector (`503`) and invalid input (`400`).\n\n";
  return md;
}

/** Tokens, the resource name and the typed client: what a UI needs before its first call. */
function renderTokens(): string {
  return (
    "## Tokens\n\n" +
    `**The resource is named after MCP.** The connector is one OAuth protected resource, \`https://<your connector>${RESOURCE_PATH}\`, for its MCP endpoint and this API alike. Ask for tokens with \`resource=https://<your connector>${RESOURCE_PATH}\`; the resource's metadata is at \`/.well-known/oauth-protected-resource${RESOURCE_PATH}\`, and the \`401\` challenge on \`${API_BASE}\` points there. There is no separate \`${API_BASE}\` resource: RFC 9728 ties a metadata document to the identifier its address was built from, so an alias would mean a second resource and a second token audience, a wider token for the sake of a name.\n\n` +
    "**Refresh one at a time.** Access tokens live 5 minutes. Refresh tokens rotate on every use, and presenting one twice revokes the whole connection (reuse detection). A UI that sends reads in parallel must let exactly one of them refresh and have the others wait for it, and must not refresh when another read already did.\n\n" +
    "## Typed client\n\n" +
    "`schoolsoft-agent/client` is a small client for JavaScript and TypeScript apps. It imports nothing but Zod, so a bundler (Metro, Vite) pulls in no connector code. It calls every route above, validates every answer against the schemas this reference is generated from (fields it does not know pass through), refreshes tokens one at a time as described above, and reports every failure as a `ConnectorError` with the `kind`, `retryable` and problem name the MCP tools and the CLI use. Signing in (registration, PKCE and the redirect) stays with the app; the client starts from the tokens it received. Design: [OpenAPI and typed client spec](../planning/specs/2026-09-26-openapi-client.md).\n\n" +
    "```ts\n" +
    'import { createClient, memoryTokenStore, ConnectorError } from "schoolsoft-agent/client";\n\n' +
    "const client = createClient({\n" +
    '  baseUrl: "https://connector.example",\n' +
    "  clientId, // from POST /register\n" +
    "  tokens: memoryTokenStore({ accessToken, refreshToken, expiresAt }),\n" +
    "});\n" +
    "try {\n" +
    "  const overview = await client.overview(childId);\n" +
    '  if (overview.lunch.status === "ok") show(overview.lunch.data.days);\n' +
    "} catch (error) {\n" +
    '  if (error instanceof ConnectorError && error.problem === "schoolsoft-session")\n' +
    "    askParentToSignIn(error.ownerDashboard);\n" +
    "}\n" +
    "```\n\n" +
    "| Method | Route |\n|---|---|\n" +
    "| `session()` | `GET /api/v1/session` |\n" +
    "| `children()` | `GET /api/v1/children` |\n" +
    "| `schedule(childId, { week, fresh })` | `GET /api/v1/children/{childId}/schedule` |\n" +
    "| `calendar(childId, { start_date, end_date, fresh })` | `GET /api/v1/children/{childId}/calendar` |\n" +
    "| `lunchMenu(childId, { week, fresh })` | `GET /api/v1/children/{childId}/lunch-menu` |\n" +
    "| `overview(childId, { date, fresh })` | `GET /api/v1/children/{childId}/overview` |\n\n" +
    "| Failure | `kind` | `problem` | `retryable` |\n|---|---|---|---|\n" +
    "| Any problem details answer | the body's | the body's type | the body's |\n" +
    "| `401` that survives one refresh, a refused refresh, or no tokens | `not_authenticated` | `oauth-token` | false |\n" +
    "| The connector cannot be reached | `network` | null | true |\n" +
    "| An answer that does not fit its schema | `upstream` | `response-drift` | false |\n" +
    "| Any other answer (e.g. a proxy's error page) | `upstream` | null | for 5xx |\n\n" +
    "The client never retries on its own, except once after a refresh; honour `retryAt` and `Retry-After`.\n\n"
  );
}

export function renderRestApi(): string {
  const routes = restRoutes();
  let md =
    HEADER +
    "# REST API (parent-hosted connector)\n\n" +
    "Read-only JSON for custom UIs, served by the [parent-hosted connector](../deployment/connector.md) at `https://<your connector>/api/v1`. " +
    "The routes are generated from the same operations as the connector's MCP tools, behind the same OAuth access tokens, scopes and per-child approval: an app gets a token through the ordinary connection approval and sends it as `Authorization: Bearer <token>`. " +
    "There are no cookies or API keys. Same-origin only: no CORS headers are sent and a request with another site's `Origin` is refused. " +
    `Each caller may make ${REST_REQUESTS_PER_MINUTE} requests per minute. Design: [REST surface spec](../planning/specs/2026-09-26-rest-surface.md).\n\n` +
    "Responses are the operations' validated domain objects, unchanged, as `application/json`. Failures are `application/problem+json` (see [Problems](#problems)). " +
    "The same API as an OpenAPI 3.1 document: [openapi.json](openapi.json); a typed client for JavaScript and TypeScript apps: [`schoolsoft-agent/client`](#typed-client).\n\n";
  md += "| Route | Operation | Scope | Query parameters |\n|---|---|---|---|\n";
  md += "| `GET /api/v1/session` | (connection status) | any | none |\n";
  for (const route of routes)
    md += `| \`GET ${route.path}\` | \`${route.operation.name}\` | \`${route.operation.name}\` | ${route.query.map((q) => `\`${q.name}\``).join(", ") || "none"} |\n`;
  md += `| \`GET ${OVERVIEW_PATH}\` | (composite) | any of ${OVERVIEW_SCOPES.map((s) => `\`${s}\``).join(", ")} | ${OVERVIEW_QUERY.query.map((q) => `\`${q.name}\``).join(", ")} |\n`;
  md += "\n## `GET /api/v1/session`\n\n";
  md +=
    'What the calling connection may do and whether the connector can serve it now. Never starts a SchoolSoft login or BankID; it only restores the saved session silently, as the owner dashboard does. Show data when `schoolsoft.signedIn` is true; otherwise link the parent to `ownerDashboard`, unless `schoolsoft.portal.state` is not `ok`: then the school portal is pushing back, signing in again does not help, and the UI shows "try again at `retryAt`" instead.\n\n' +
    outputTable(SessionSchema);
  for (const route of routes) {
    const op = route.operation;
    md += `## \`GET ${route.path}\`\n\n${op.title}. Operation \`${op.name}\`, scope \`${op.name}\`.`;
    md += route.childScoped
      ? " `{childId}` is an `id` from `/children`; a child outside the connection's approval is refused with `403` before anything is read.\n\n"
      : "\n\n";
    if (route.query.length) {
      md += "| Query parameter | Type | Description |\n|---|---|---|\n";
      for (const q of route.query) md += `| \`${q.name}\` | ${q.kind} | ${q.description} |\n`;
      md += "\n";
    }
    if (op.name === "list_children")
      md +=
        "Output (the connector's projection: only the children in this connection, no guardian name):\n\n" +
        outputTable(ConnectorChildrenSchema);
    else
      md +=
        "Output (validated; an answer that does not fit is a `502` `response-drift`):\n\n" +
        outputTable(op.output!);
  }
  md += renderOverview();
  md += renderTokens();
  md += "## Problems\n\n";
  md +=
    `Every failure after the token check is \`application/problem+json\` (RFC 9457): \`type\` (\`${PROBLEM_TYPE_PREFIX}<name>\`), \`title\`, \`status\`, \`detail\` (the message), \`hint\` (what to do next), \`kind\` and \`retryable\` (as the MCP tools and CLI report them), \`ownerDashboard\` on SchoolSoft-session problems, \`retryAt\` (with a \`Retry-After\` header) when the school portal is pushing back, and \`error\` (\`invalid_token\` or \`insufficient_scope\`) on token problems. ` +
    "`detail` and `hint` are in Swedish or English, chosen by `Accept-Language` (else the connector's `SCHOOLSOFT_LANG`, else English); `Content-Language` says which. " +
    "A missing, invalid or expired token is answered by the MCP SDK's bearer check with `401`, an RFC 6750 body and `WWW-Authenticate`, exactly as on `/mcp`.\n\n" +
    "**`401` is about the app's token; `409` is about the connector's SchoolSoft sign-in.** On `401`, refresh the token and connect again if that fails. On `409` the token is fine and retrying cannot help: send the parent to `ownerDashboard` to sign in with BankID.\n\n";
  md += "| Status | `type` name | Title | Meaning |\n|---|---|---|---|\n";
  for (const [name, problem] of Object.entries(PROBLEMS))
    md += `| ${problem.status} | \`${name}\` | ${problem.title} | ${problem.meaning} |\n`;
  return md;
}

/** The OpenAPI document, as committed. */
export function renderOpenApi(): string {
  return JSON.stringify(openApiDocument(), null, 2) + "\n";
}

interface Parameter {
  name: string;
  in: string;
  schema: Record<string, unknown>;
  description?: string;
}
interface OpenApiOperation {
  operationId: string;
  parameters: Parameter[];
  responses: { "200": { content: { "application/json": { schema: { $ref: string } } } } };
}

/** The typed client's generated half: response schemas, their types and the route table. */
export function renderClientApi(): string {
  const doc = openApiDocument() as {
    paths: Record<string, { get: OpenApiOperation }>;
    components: { schemas: Record<string, Record<string, unknown>> };
  };
  const schemas = doc.components.schemas;
  const names = Object.keys(schemas);
  const problem = schemas.Problem as { properties: { kind: { enum: string[] } } };
  let ts =
    "// Generated by `make docs` from the connector's route table and Zod schemas (src/http). Do not edit by hand.\n" +
    "// The same schemas describe docs/reference/openapi.json.\n\n" +
    `/** The REST base path below the connector's origin. */\nexport const API_BASE = ${JSON.stringify(API_BASE)};\n` +
    `/** The API version (the \`v1\` in the path). */\nexport const API_VERSION = ${JSON.stringify(API_VERSION)};\n` +
    `/** The OAuth resource path: tokens are for \`<connector origin>${RESOURCE_PATH}\`, also for REST. */\nexport const RESOURCE_PATH = ${JSON.stringify(RESOURCE_PATH)};\n\n` +
    `/** The error kinds, as the MCP tools and the CLI report them. */\nexport type ErrorKind = ${tsType({ enum: problem.properties.kind.enum })};\n` +
    `/** The problem type names (the part of \`type\` after \`${PROBLEM_TYPE_PREFIX}\`). */\nexport type ProblemName = ${tsType({ enum: Object.keys(PROBLEMS) })};\n\n` +
    `export type SchemaName = ${tsType({ enum: names })};\n\n`;
  for (const name of names) ts += tsDeclaration(name, schemas[name]) + "\n";
  const routes: string[] = [];
  const members: string[] = [];
  for (const [path, { get }] of Object.entries(doc.paths)) {
    const id = get.operationId;
    const query = get.parameters.filter((p) => p.in === "query");
    const childScoped = get.parameters.some((p) => p.in === "path");
    const type = id.charAt(0).toUpperCase() + id.slice(1) + "Query";
    ts += `/** Query parameters of \`GET ${API_BASE}${path}\`. */\nexport type ${type} = ${tsType({
      type: "object",
      properties: Object.fromEntries(
        query.map((p) => [p.name, { ...p.schema, description: p.description }]),
      ),
    })};\n\n`;
    const schema = get.responses["200"].content["application/json"].schema.$ref.split("/").pop()!;
    members.push(`  ${id}: { query: ${type}; response: ${schema}; childScoped: ${childScoped} };`);
    routes.push(
      `  ${id}: { path: ${JSON.stringify(path)}, schema: ${JSON.stringify(schema)}, childScoped: ${childScoped}, query: ${JSON.stringify(query.map((p) => p.name))} },`,
    );
  }
  ts += `/** Every route by operation id: its query, its answer and whether it names a child. */\nexport interface Operations {\n${members.join("\n")}\n}\n\n`;
  ts +=
    "export interface Route {\n  path: string;\n  schema: SchemaName;\n  childScoped: boolean;\n  query: readonly string[];\n}\n\n" +
    `/** The route table (paths below API_BASE). */\nexport const ROUTES: { readonly [K in keyof Operations]: Route & { childScoped: Operations[K]["childScoped"] } } = {\n${routes.join("\n")}\n};\n\n`;
  ts += `/** The answers' JSON Schemas; the client turns each into a validator once. */\nexport const SCHEMAS: Record<SchemaName, Record<string, unknown>> = ${JSON.stringify(schemas, null, 2)};\n`;
  return ts;
}

export const OUTPUTS: Record<string, () => string> = {
  "docs/reference/tools.md": renderTools,
  "docs/reference/commands.md": renderCommands,
  "skills/schoolsoft/references/commands.md": renderCommands,
  "docs/reference/rest-api.md": renderRestApi,
  "docs/reference/openapi.json": renderOpenApi,
  "src/client/api.gen.ts": renderClientApi,
};

if (process.argv[1] && /gen-docs\.(ts|js)$/.test(process.argv[1])) {
  for (const [rel, render] of Object.entries(OUTPUTS)) {
    const file = join(process.cwd(), rel);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, render());
    console.log("wrote", rel);
  }
}
