/**
 * Generate reference docs from the operation registry:
 *   docs/reference/tools.md                     (MCP tools)
 *   docs/reference/commands.md                  (CLI commands)
 *   skills/schoolsoft/references/commands.md    (same, for the skill)
 *   docs/reference/rest-api.md                  (the connector's REST routes and problems)
 * A boundary test asserts the committed files equal this output.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { z } from "zod";
import { operations } from "../src/core/index.js";
import { flagsFromSchema, kebab } from "../src/cli/flags.js";
import { TOOL_PREFIX } from "../src/mcp/server.js";
import { restRoutes } from "../src/http/routes.js";
import { PROBLEMS, PROBLEM_TYPE_PREFIX } from "../src/http/problem.js";
import { REST_REQUESTS_PER_MINUTE } from "../src/http/rest.js";

const HEADER =
  "<!-- Generated by `make docs` from src/core/operations — do not edit by hand. -->\n\n";

function annotationBadges(op: (typeof operations)[number]): string {
  const a = op.annotations;
  return [
    a.readOnly ? "read-only" : "writes",
    a.destructive ? "destructive" : null,
    a.idempotent ? "idempotent" : null,
    a.requiresAuth ? "needs login" : "no login needed",
  ]
    .filter(Boolean)
    .join(", ");
}

function exampleArgs(op: (typeof operations)[number]): Record<string, unknown> {
  const ex: Record<string, unknown> = {};
  for (const s of flagsFromSchema(op.input)) {
    if (!s.required) continue;
    ex[s.key] =
      s.kind === "number"
        ? 1
        : s.kind === "boolean"
          ? true
          : s.kind === "enum"
            ? s.choices?.[0]
            : "Rösjöskolan";
  }
  if (op.name === "get_schedule") ex.week = 37;
  return ex;
}

interface JsonNode {
  type?: string | string[];
  format?: string;
  const?: unknown;
  enum?: unknown[];
  description?: string;
  anyOf?: JsonNode[];
  items?: JsonNode;
  properties?: Record<string, JsonNode>;
}

/** A JSON Schema node as a short type, e.g. `string (date-time)`, `object or null`. */
function typeName(node: JsonNode): string {
  if (node.anyOf) return node.anyOf.map(typeName).join(" or ");
  if (node.const !== undefined) return `\`${JSON.stringify(node.const)}\``;
  if (node.enum) return node.enum.map((v) => `\`${JSON.stringify(v)}\``).join(" \\| ");
  if (node.type === "array") return `${typeName(node.items!)}[]`;
  const type = Array.isArray(node.type) ? node.type.join(" or ") : node.type!;
  return node.format ? `${type} (${node.format})` : type;
}

/** One row per field, nested objects and array items flattened into dotted paths. */
function outputRows(node: JsonNode, path: string, rows: string[][]): string[][] {
  const object =
    node.type === "object"
      ? node
      : node.type === "array"
        ? node.items!.type === "object"
          ? node.items
          : undefined
        : node.anyOf?.find((n) => n.type === "object");
  for (const [key, child] of Object.entries(object?.properties ?? {})) {
    const at = path ? `${path}${node.type === "array" ? "[]" : ""}.${key}` : key;
    rows.push([`\`${at}\``, typeName(child), child.description ?? ""]);
    outputRows(child, at, rows);
  }
  return rows;
}

/** The field table of a typed operation's output schema. */
function outputTable(output: z.ZodType): string {
  const schema = z.toJSONSchema(output, { io: "output" }) as JsonNode;
  let md = "| Field | Type | Description |\n|---|---|---|\n";
  for (const row of outputRows(schema, "", [])) md += `| ${row.join(" | ")} |\n`;
  return md + "\n";
}

/** The validated result shape of a typed operation, generated from its output schema. */
export function renderOutput(op: (typeof operations)[number]): string {
  if (!op.output) return "";
  return (
    "Output (validated; a response that does not fit is a `response_drift` error, exit 7):\n\n" +
    outputTable(op.output)
  );
}

export function renderTools(): string {
  let md =
    HEADER +
    "# MCP tools\n\nServer: `schoolsoft-agent-mcp` (stdio). Every tool returns JSON as `structuredContent` plus a text copy (truncated at 25 000 characters). Tools with an Output table declare it as their `outputSchema`; their results are validated and always carry `structuredContent`, and their errors are the two text lines only.\n\n";
  md += "| Tool | Purpose | Annotations |\n|---|---|---|\n";
  for (const op of operations)
    md += `| \`${TOOL_PREFIX}${op.name}\` | ${op.title} | ${annotationBadges(op)} |\n`;
  md += "\n";
  for (const op of operations) {
    md += `## \`${TOOL_PREFIX}${op.name}\`\n\n${op.description.trim()}\n\n`;
    const specs = flagsFromSchema(op.input);
    if (specs.length) {
      md += "| Argument | Type | Required | Description |\n|---|---|---|---|\n";
      for (const s of specs)
        md += `| \`${s.key}\` | ${s.kind}${s.choices ? ` (${s.choices.join(" \\| ")})` : ""} | ${s.required ? "yes" : "no"} | ${s.description} |\n`;
      md += "\n";
    } else {
      md += "_No arguments._\n\n";
    }
    md += renderOutput(op);
    md +=
      "Example call:\n\n```json\n" +
      JSON.stringify({ name: TOOL_PREFIX + op.name, arguments: exampleArgs(op) }, null, 2) +
      "\n```\n\n";
  }
  return md;
}

export function renderCommands(): string {
  let md =
    HEADER +
    "# CLI commands\n\nBinary: `schoolsoft-agent`. Output is JSON on stdout; errors are one line on stderr.\n\n";
  md +=
    "Exit codes: `0` ok · `1` bug · `2` not authenticated (run `login`) · `3` not configured (run `configure`) · `4` network · `5` not available · `6` input · `7` upstream (including `response_drift`: the portal's answer changed shape).\n\n";
  md +=
    "Global flags: `--school <slug>`, `--org-id <id>`, `--config-dir <dir>`, `--state-dir <dir>`, `--pretty`.\n\n";
  md += "| Command | Purpose | Annotations |\n|---|---|---|\n";
  for (const op of operations)
    md += `| \`${kebab(op.name)}\` | ${op.title} | ${annotationBadges(op)} |\n`;
  md +=
    "| `configure` | Write config.json (interactive school lookup or `--school/--org-id/--query`) | no login needed |\n";
  md +=
    "| `doctor` | Diagnose environment, config, session, connectivity (`--fix` migrates a legacy store) | no login needed |\n";
  md +=
    "| `doctor --verify` | Check that each typed read still parses against the live portal; prints statuses, never data (`--all-children` checks every child) | read-only, needs a saved session; exit 7 on drift |\n\n";
  for (const op of operations) {
    md += `## \`schoolsoft-agent ${kebab(op.name)}\`\n\n${op.description.trim()}\n\n`;
    const specs = flagsFromSchema(op.input);
    if (specs.length) {
      md += "| Flag | Required | Description |\n|---|---|---|\n";
      for (const s of specs)
        md += `| \`${s.flag}\` | ${s.required ? "yes" : "no"} | ${s.description}${s.choices ? ` (${s.choices.join(", ")})` : ""} |\n`;
      md += "\n";
    }
    md += renderOutput(op);
    const ex = exampleArgs(op);
    const flags = Object.entries(ex)
      .map(([k, v]) =>
        typeof v === "boolean" ? `--${kebab(k)}` : `--${kebab(k)} ${JSON.stringify(v)}`,
      )
      .join(" ");
    md += "```bash\nschoolsoft-agent " + kebab(op.name) + (flags ? " " + flags : "") + "\n```\n\n";
  }
  return md;
}

/** The connector's projection of list_children (runtime.ts): granted children only. */
const CONNECTOR_CHILDREN = z.object({
  children: z
    .array(z.object({ id: z.number().int(), firstName: z.string() }))
    .describe("The children in this connection, { id, firstName }"),
  childInFocus: z
    .number()
    .int()
    .nullable()
    .describe("The child reads default to, when it is in this grant; else null"),
});

export function renderRestApi(): string {
  const routes = restRoutes();
  let md =
    HEADER +
    "# REST API (parent-hosted connector)\n\n" +
    "Read-only JSON for custom UIs, served by the [parent-hosted connector](../deployment/connector.md) at `https://<your connector>/api/v1`. " +
    "The routes are generated from the same operations as the connector's MCP tools, behind the same OAuth access tokens, scopes and per-child approval: an app gets a token through the ordinary connection approval and sends it as `Authorization: Bearer <token>`. " +
    "There are no cookies or API keys. Same-origin only: no CORS headers are sent and a request with another site's `Origin` is refused. " +
    `Each caller may make ${REST_REQUESTS_PER_MINUTE} requests per minute. Design: [REST surface spec](../planning/specs/2026-09-26-rest-surface.md).\n\n` +
    "Responses are the operations' validated domain objects, unchanged, as `application/json`. Failures are `application/problem+json` (see [Problems](#problems)).\n\n";
  md += "| Route | Operation | Scope | Query parameters |\n|---|---|---|---|\n";
  md += "| `GET /api/v1/session` | (connection status) | any | none |\n";
  for (const route of routes)
    md += `| \`GET ${route.path}\` | \`${route.operation.name}\` | \`${route.operation.name}\` | ${route.query.map((q) => `\`${q.name}\``).join(", ") || "none"} |\n`;
  md += "\n## `GET /api/v1/session`\n\n";
  md +=
    "What the calling connection may do and whether the connector can serve it now. Never starts a SchoolSoft login or BankID; it only restores the saved session silently, as the owner dashboard does. Show data when `schoolsoft.signedIn` is true; otherwise link the parent to `ownerDashboard`.\n\n" +
    "| Field | Type | Description |\n|---|---|---|\n" +
    "| `schoolsoft.signedIn` | boolean | The connector's SchoolSoft session is present and valid |\n" +
    "| `schoolsoft.loginInProgress` | boolean | The parent started a sign-in that has not finished |\n" +
    "| `schoolsoft.webSession` | boolean | A gated web-login session is stored (the connector does not offer one; always false today) |\n" +
    "| `children[]` | object[] | The children this connection may read, `{ id, firstName }` as `/children` returns them; empty while signed out |\n" +
    "| `scopes` | string[] | The operations this token may call |\n" +
    "| `routes[]` | object[] | `{ operation, method, path }` for each route the scopes allow |\n" +
    "| `ownerDashboard` | string | Where the parent signs in to SchoolSoft again |\n" +
    "| `connectionExpiresAt` | string (date-time) | When this connection's approval expires |\n\n";
  for (const route of routes) {
    const op = route.operation;
    md += `## \`GET ${route.path}\`\n\n${op.title}. Operation \`${op.name}\`, scope \`${op.name}\`.`;
    md += route.childScoped
      ? " `{childId}` is an `id` from `/children`; a child outside the connection's approval is refused with `403` before anything is read.\n\n"
      : "\n\n";
    if (route.query.length) {
      md += "| Query parameter | Type | Description |\n|---|---|---|\n";
      for (const q of route.query) md += `| \`${q.name}\` | ${q.kind} | ${q.description} |\n`;
      md += "\n";
    }
    if (op.name === "list_children")
      md +=
        "Output (the connector's projection: only the children in this connection, no guardian name):\n\n" +
        outputTable(CONNECTOR_CHILDREN);
    else
      md +=
        "Output (validated; an answer that does not fit is a `502` `response-drift`):\n\n" +
        outputTable(op.output!);
  }
  md += "## Problems\n\n";
  md +=
    `Every failure after the token check is \`application/problem+json\` (RFC 9457): \`type\` (\`${PROBLEM_TYPE_PREFIX}<name>\`), \`title\`, \`status\`, \`detail\` (the message), \`hint\` (what to do next), \`kind\` and \`retryable\` (as the MCP tools and CLI report them), \`ownerDashboard\` on SchoolSoft-session problems and \`error\` (\`invalid_token\` or \`insufficient_scope\`) on token problems. ` +
    "`detail` and `hint` are in Swedish or English, chosen by `Accept-Language` (else the connector's `SCHOOLSOFT_LANG`, else English); `Content-Language` says which. " +
    "A missing, invalid or expired token is answered by the MCP SDK's bearer check with `401`, an RFC 6750 body and `WWW-Authenticate`, exactly as on `/mcp`.\n\n" +
    "**`401` is about the app's token; `409` is about the connector's SchoolSoft sign-in.** On `401`, refresh the token and connect again if that fails. On `409` the token is fine and retrying cannot help: send the parent to `ownerDashboard` to sign in with BankID.\n\n";
  md += "| Status | `type` name | Title | Meaning |\n|---|---|---|---|\n";
  for (const [name, problem] of Object.entries(PROBLEMS))
    md += `| ${problem.status} | \`${name}\` | ${problem.title} | ${problem.meaning} |\n`;
  return md;
}

export const OUTPUTS: Record<string, () => string> = {
  "docs/reference/tools.md": renderTools,
  "docs/reference/commands.md": renderCommands,
  "skills/schoolsoft/references/commands.md": renderCommands,
  "docs/reference/rest-api.md": renderRestApi,
};

if (process.argv[1] && /gen-docs\.(ts|js)$/.test(process.argv[1])) {
  for (const [rel, render] of Object.entries(OUTPUTS)) {
    const file = join(process.cwd(), rel);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, render());
    console.log("wrote", rel);
  }
}
