/**
 * Generate reference docs from the operation registry:
 *   docs/reference/tools.md                     (MCP tools)
 *   docs/reference/commands.md                  (CLI commands)
 *   skills/schoolsoft/references/commands.md    (same, for the skill)
 * A boundary test asserts the committed files equal this output.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { operations } from "../src/core/index.js";
import { flagsFromSchema, kebab } from "../src/cli/flags.js";
import { TOOL_PREFIX } from "../src/mcp/server.js";

const HEADER =
  "<!-- Generated by `make docs` from src/core/operations — do not edit by hand. -->\n\n";

function annotationBadges(op: (typeof operations)[number]): string {
  const a = op.annotations;
  return [
    a.readOnly ? "read-only" : "writes",
    a.destructive ? "destructive" : null,
    a.idempotent ? "idempotent" : null,
    a.requiresAuth ? "needs login" : "no login needed",
  ]
    .filter(Boolean)
    .join(", ");
}

function exampleArgs(op: (typeof operations)[number]): Record<string, unknown> {
  const ex: Record<string, unknown> = {};
  for (const s of flagsFromSchema(op.input)) {
    if (!s.required) continue;
    ex[s.key] =
      s.kind === "number"
        ? 1
        : s.kind === "boolean"
          ? true
          : s.kind === "enum"
            ? s.choices?.[0]
            : "Rösjöskolan";
  }
  if (op.name === "get_schedule") ex.week = 37;
  return ex;
}

export function renderTools(): string {
  let md =
    HEADER +
    "# MCP tools\n\nServer: `schoolsoft-agent-mcp` (stdio). Every tool returns JSON as `structuredContent` plus a text copy (truncated at 25 000 characters).\n\n";
  md += "| Tool | Purpose | Annotations |\n|---|---|---|\n";
  for (const op of operations)
    md += `| \`${TOOL_PREFIX}${op.name}\` | ${op.title} | ${annotationBadges(op)} |\n`;
  md += "\n";
  for (const op of operations) {
    md += `## \`${TOOL_PREFIX}${op.name}\`\n\n${op.description.trim()}\n\n`;
    const specs = flagsFromSchema(op.input);
    if (specs.length) {
      md += "| Argument | Type | Required | Description |\n|---|---|---|---|\n";
      for (const s of specs)
        md += `| \`${s.key}\` | ${s.kind}${s.choices ? ` (${s.choices.join(" \\| ")})` : ""} | ${s.required ? "yes" : "no"} | ${s.description} |\n`;
      md += "\n";
    } else {
      md += "_No arguments._\n\n";
    }
    md +=
      "Example call:\n\n```json\n" +
      JSON.stringify({ name: TOOL_PREFIX + op.name, arguments: exampleArgs(op) }, null, 2) +
      "\n```\n\n";
  }
  return md;
}

export function renderCommands(): string {
  let md =
    HEADER +
    "# CLI commands\n\nBinary: `schoolsoft-agent`. Output is JSON on stdout; errors are one line on stderr.\n\n";
  md +=
    "Exit codes: `0` ok · `1` error · `2` not authenticated (run `login`) · `3` not configured (run `configure`).\n\n";
  md +=
    "Global flags: `--school <slug>`, `--org-id <id>`, `--config-dir <dir>`, `--state-dir <dir>`, `--pretty`.\n\n";
  md += "| Command | Purpose | Annotations |\n|---|---|---|\n";
  for (const op of operations)
    md += `| \`${kebab(op.name)}\` | ${op.title} | ${annotationBadges(op)} |\n`;
  md +=
    "| `configure` | Write config.json (interactive school lookup or `--school/--org-id/--query`) | no login needed |\n";
  md +=
    "| `doctor` | Diagnose environment, config, session, connectivity (`--fix` migrates a legacy store) | no login needed |\n\n";
  for (const op of operations) {
    md += `## \`schoolsoft-agent ${kebab(op.name)}\`\n\n${op.description.trim()}\n\n`;
    const specs = flagsFromSchema(op.input);
    if (specs.length) {
      md += "| Flag | Required | Description |\n|---|---|---|\n";
      for (const s of specs)
        md += `| \`${s.flag}\` | ${s.required ? "yes" : "no"} | ${s.description}${s.choices ? ` (${s.choices.join(", ")})` : ""} |\n`;
      md += "\n";
    }
    const ex = exampleArgs(op);
    const flags = Object.entries(ex)
      .map(([k, v]) =>
        typeof v === "boolean" ? `--${kebab(k)}` : `--${kebab(k)} ${JSON.stringify(v)}`,
      )
      .join(" ");
    md += "```bash\nschoolsoft-agent " + kebab(op.name) + (flags ? " " + flags : "") + "\n```\n\n";
  }
  return md;
}

export const OUTPUTS: Record<string, () => string> = {
  "docs/reference/tools.md": renderTools,
  "docs/reference/commands.md": renderCommands,
  "skills/schoolsoft/references/commands.md": renderCommands,
};

if (process.argv[1] && /gen-docs\.(ts|js)$/.test(process.argv[1])) {
  for (const [rel, render] of Object.entries(OUTPUTS)) {
    const file = join(process.cwd(), rel);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, render());
    console.log("wrote", rel);
  }
}
