// Generated by `make docs` from the connector's route table and Zod schemas (src/http). Do not edit by hand.
// The same schemas describe docs/reference/openapi.json.

/** The REST base path below the connector's origin. */
export const API_BASE = "/api/v1";
/** The API version (the `v1` in the path). */
export const API_VERSION = "1";
/** The OAuth resource path: tokens are for `<connector origin>/mcp`, also for REST. */
export const RESOURCE_PATH = "/mcp";

/** The error kinds, as the MCP tools and the CLI report them. */
export type ErrorKind = "internal" | "not_authenticated" | "not_configured" | "network" | "not_available" | "input" | "upstream";
/** The problem type names (the part of `type` after `urn:schoolsoft-agent:problem:`). */
export type ProblemName = "invalid-input" | "oauth-token" | "scope-not-granted" | "child-not-permitted" | "foreign-origin" | "not-found" | "schoolsoft-session" | "web-session" | "rate-limited" | "internal" | "not-implemented" | "response-drift" | "upstream" | "connector-busy" | "portal-pushback" | "not-available" | "network";

export type SchemaName = "Session" | "Children" | "Schedule" | "Calendar" | "LunchMenu" | "Overview" | "Problem";

export type Session = {
  schoolsoft: {
    /** The connector's SchoolSoft session is present and valid */
    signedIn: boolean;
    /** The parent started a sign-in that has not finished */
    loginInProgress: boolean;
    /** A gated web-login session is stored (the connector does not offer one; always false today) */
    webSession: boolean;
    portal: {
      /** `ok`: requests to the school portal flow; `backing_off`: a short pause after the portal pushed back; `paused`: the portal pushed back repeatedly and the connector sends it nothing until `retryAt`; `probing`: the next request tests whether it answers again */
      state: "ok" | "backing_off" | "paused" | "probing";
      /** When requests flow again; null while they flow or a probe decides */
      retryAt: string | null;
    };
  };
  /** The children this connection may read, { id, firstName } as /children returns them; empty while signed out */
  children: Array<{
    /** Child id; use it as {childId} */
    id: number;
    firstName: string;
  }>;
  /** The operations this token may call */
  scopes: string[];
  /** { operation, method, path } for each route the scopes allow */
  routes: Array<{
    operation: string;
    method: "GET";
    path: string;
  }>;
  /** Where the parent signs in to SchoolSoft again */
  ownerDashboard: string;
  /** When this connection's approval expires */
  connectionExpiresAt: string;
};

export type Children = {
  /** The children in this connection, { id, firstName } */
  children: Array<{
    /** Child id; use it as {childId} */
    id: number;
    firstName: string;
  }>;
  /** The child reads default to, when it is in this grant; else null */
  childInFocus: number | null;
};

export type Schedule = {
  /** ISO week-year: the year in which this week starts nearest today */
  year: number;
  week: number;
  /** Monday of the week, YYYY-MM-DD in Europe/Stockholm */
  startDate: string;
  /** Sunday of the week, YYYY-MM-DD in Europe/Stockholm */
  endDate: string;
  /** The child the result is for */
  child: {
    /** Child id; pass it as child_id */
    id: number;
    firstName: string;
  };
  lessons: Array<{
    /** Stable id of this lesson occurrence */
    id: string;
    /** Subject or lesson name */
    title: string;
    /** ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00 */
    start: string;
    /** ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00 */
    end: string;
    /** Room; null when not given */
    room: string | null;
    /** Teaching group; null when not given */
    group: string | null;
    /** Teacher; null when not given */
    teacher: string | null;
    /** Lesson description; null when not given */
    note: string | null;
  }>;
};

export type Calendar = {
  /** Calendar date YYYY-MM-DD in Europe/Stockholm */
  startDate: string;
  /** Calendar date YYYY-MM-DD in Europe/Stockholm */
  endDate: string;
  timezone: "Europe/Stockholm";
  /** The child the result is for */
  child: {
    /** Child id; pass it as child_id */
    id: number;
    firstName: string;
  };
  events: Array<{
    /** Stable id of this calendar entry */
    id: string;
    /** A timetable entry or a school event */
    kind: "lesson" | "event";
    title: string;
    allDay: boolean;
    /** Date for date-only entries */
    start: string;
    /** Date for date-only entries */
    end: string;
    /** Room or place; null when not given */
    location: string | null;
    /** Teacher; null when not given */
    teacher: string | null;
    /** Teaching group; null when not given */
    group: string | null;
    /** Portal category, e.g. lesson or lunch; null when not given */
    category: string | null;
    /** Description; null when not given */
    note: string | null;
  }>;
};

export type LunchMenu = {
  /** ISO week-year */
  year: number;
  week: number;
  /** The child the result is for */
  child: {
    /** Child id; pass it as child_id */
    id: number;
    firstName: string;
  };
  days: Array<{
    /** Calendar date YYYY-MM-DD in Europe/Stockholm */
    date: string;
    /** 1 = Monday … 7 = Sunday */
    weekday: number;
    dishes: Array<{
      /** Kind of meal, as the school names it; null when not given */
      kind: string | null;
      description: string;
    }>;
  }>;
};

export type Overview = {
  /** The child in the path */
  child: {
    /** Child id; pass it as child_id */
    id: number;
    firstName: string;
    /** School name; null when not given */
    schoolName: string | null;
    /** Class name; null when not given */
    className: string | null;
  };
  week: {
    /** ISO week-year */
    year: number;
    /** ISO week number */
    week: number;
    /** Monday of the week */
    startDate: string;
    /** Sunday of the week */
    endDate: string;
    /** Today in Europe/Stockholm, the start of nextEvent's search */
    today: string;
    timezone: "Europe/Stockholm";
  };
  /** The week's lessons: get_schedule's output */
  schedule: ({
    status: "ok";
    data: {
      /** ISO week-year: the year in which this week starts nearest today */
      year: number;
      week: number;
      /** Monday of the week, YYYY-MM-DD in Europe/Stockholm */
      startDate: string;
      /** Sunday of the week, YYYY-MM-DD in Europe/Stockholm */
      endDate: string;
      /** The child the result is for */
      child: {
        /** Child id; pass it as child_id */
        id: number;
        firstName: string;
      };
      lessons: Array<{
        /** Stable id of this lesson occurrence */
        id: string;
        /** Subject or lesson name */
        title: string;
        /** ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00 */
        start: string;
        /** ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00 */
        end: string;
        /** Room; null when not given */
        room: string | null;
        /** Teaching group; null when not given */
        group: string | null;
        /** Teacher; null when not given */
        teacher: string | null;
        /** Lesson description; null when not given */
        note: string | null;
      }>;
    };
  }) | ({
    status: "not-granted";
    /** The scope this connection lacks; nothing was read */
    scope: string;
  }) | ({
    status: "error";
    problem: {
      /** `urn:schoolsoft-agent:problem:<name>`; branch on this */
      type: string;
      /** Short English title of the problem type */
      title: string;
      /** The HTTP status this problem is answered with */
      status: number;
      /** What happened, in the negotiated language */
      detail: string;
      /** What to do next, in the negotiated language */
      hint?: string;
      /** The error kind, as the MCP tools and the CLI report it */
      kind: "internal" | "not_authenticated" | "not_configured" | "network" | "not_available" | "input" | "upstream";
      /** Whether repeating the same request may succeed */
      retryable: boolean;
      /** Where the parent signs in to SchoolSoft again (SchoolSoft-session problems) */
      ownerDashboard?: string;
      /** RFC 6750 error code on token problems */
      error?: "invalid_token" | "insufficient_scope";
      /** When the connector sends requests to the school portal again (`portal-pushback`) */
      retryAt?: string;
    };
  });
  /** The week's lunch: get_lunch_menu's output */
  lunch: ({
    status: "ok";
    data: {
      /** ISO week-year */
      year: number;
      week: number;
      /** The child the result is for */
      child: {
        /** Child id; pass it as child_id */
        id: number;
        firstName: string;
      };
      days: Array<{
        /** Calendar date YYYY-MM-DD in Europe/Stockholm */
        date: string;
        /** 1 = Monday … 7 = Sunday */
        weekday: number;
        dishes: Array<{
          /** Kind of meal, as the school names it; null when not given */
          kind: string | null;
          description: string;
        }>;
      }>;
    };
  }) | ({
    status: "not-granted";
    /** The scope this connection lacks; nothing was read */
    scope: string;
  }) | ({
    status: "error";
    problem: {
      /** `urn:schoolsoft-agent:problem:<name>`; branch on this */
      type: string;
      /** Short English title of the problem type */
      title: string;
      /** The HTTP status this problem is answered with */
      status: number;
      /** What happened, in the negotiated language */
      detail: string;
      /** What to do next, in the negotiated language */
      hint?: string;
      /** The error kind, as the MCP tools and the CLI report it */
      kind: "internal" | "not_authenticated" | "not_configured" | "network" | "not_available" | "input" | "upstream";
      /** Whether repeating the same request may succeed */
      retryable: boolean;
      /** Where the parent signs in to SchoolSoft again (SchoolSoft-session problems) */
      ownerDashboard?: string;
      /** RFC 6750 error code on token problems */
      error?: "invalid_token" | "insufficient_scope";
      /** When the connector sends requests to the school portal again (`portal-pushback`) */
      retryAt?: string;
    };
  });
  /** The next school event from today, within 30 days (get_calendar) */
  nextEvent: ({
    status: "ok";
    data: {
      /** The first school event (kind "event") that has not ended, by start; null when there is none */
      event: ({
        /** Stable id of this calendar entry */
        id: string;
        /** A timetable entry or a school event */
        kind: "lesson" | "event";
        title: string;
        allDay: boolean;
        /** Date for date-only entries */
        start: string;
        /** Date for date-only entries */
        end: string;
        /** Room or place; null when not given */
        location: string | null;
        /** Teacher; null when not given */
        teacher: string | null;
        /** Teaching group; null when not given */
        group: string | null;
        /** Portal category, e.g. lesson or lunch; null when not given */
        category: string | null;
        /** Description; null when not given */
        note: string | null;
      }) | null;
      /** First day searched: today in Europe/Stockholm */
      from: string;
      /** Last day searched: 29 days after today */
      until: string;
    };
  }) | ({
    status: "not-granted";
    /** The scope this connection lacks; nothing was read */
    scope: string;
  }) | ({
    status: "error";
    problem: {
      /** `urn:schoolsoft-agent:problem:<name>`; branch on this */
      type: string;
      /** Short English title of the problem type */
      title: string;
      /** The HTTP status this problem is answered with */
      status: number;
      /** What happened, in the negotiated language */
      detail: string;
      /** What to do next, in the negotiated language */
      hint?: string;
      /** The error kind, as the MCP tools and the CLI report it */
      kind: "internal" | "not_authenticated" | "not_configured" | "network" | "not_available" | "input" | "upstream";
      /** Whether repeating the same request may succeed */
      retryable: boolean;
      /** Where the parent signs in to SchoolSoft again (SchoolSoft-session problems) */
      ownerDashboard?: string;
      /** RFC 6750 error code on token problems */
      error?: "invalid_token" | "insufficient_scope";
      /** When the connector sends requests to the school portal again (`portal-pushback`) */
      retryAt?: string;
    };
  });
};

export type Problem = {
  /** `urn:schoolsoft-agent:problem:<name>`; branch on this */
  type: string;
  /** Short English title of the problem type */
  title: string;
  /** The HTTP status this problem is answered with */
  status: number;
  /** What happened, in the negotiated language */
  detail: string;
  /** What to do next, in the negotiated language */
  hint?: string;
  /** The error kind, as the MCP tools and the CLI report it */
  kind: "internal" | "not_authenticated" | "not_configured" | "network" | "not_available" | "input" | "upstream";
  /** Whether repeating the same request may succeed */
  retryable: boolean;
  /** Where the parent signs in to SchoolSoft again (SchoolSoft-session problems) */
  ownerDashboard?: string;
  /** RFC 6750 error code on token problems */
  error?: "invalid_token" | "insufficient_scope";
  /** When the connector sends requests to the school portal again (`portal-pushback`) */
  retryAt?: string;
};

/** Query parameters of `GET /api/v1/session`. */
export type GetSessionQuery = Record<string, unknown>;

/** Query parameters of `GET /api/v1/children`. */
export type ListChildrenQuery = Record<string, unknown>;

/** Query parameters of `GET /api/v1/children/{childId}/schedule`. */
export type GetScheduleQuery = {
  /** ISO week number 1–53. Defaults to the current week. */
  week?: number;
  /** Skip the short-lived in-memory copy and read from SchoolSoft now. Use only when the user asks for the very latest. */
  fresh?: boolean;
};

/** Query parameters of `GET /api/v1/children/{childId}/calendar`. */
export type GetCalendarQuery = {
  /** Inclusive start date, YYYY-MM-DD. Supply with end_date or omit both for this week. */
  start_date?: string;
  /** Inclusive end date, YYYY-MM-DD. Maximum 366 days including start and end. */
  end_date?: string;
  /** Skip the short-lived in-memory copy and read from SchoolSoft now. Use only when the user asks for the very latest. */
  fresh?: boolean;
};

/** Query parameters of `GET /api/v1/children/{childId}/lunch-menu`. */
export type GetLunchMenuQuery = {
  /** ISO week number 1–53. Defaults to the current week. */
  week?: number;
  /** Skip the short-lived in-memory copy and read from SchoolSoft now. Use only when the user asks for the very latest. */
  fresh?: boolean;
};

/** Query parameters of `GET /api/v1/children/{childId}/overview`. */
export type GetOverviewQuery = {
  /** Any day of the week to show, YYYY-MM-DD, within about half a year of today. Defaults to today in Europe/Stockholm. */
  date?: string;
  /** Skip the short-lived in-memory copy and read from SchoolSoft now. Use only when the user asks for the very latest. */
  fresh?: boolean;
};

/** Every route by operation id: its query, its answer and whether it names a child. */
export interface Operations {
  getSession: { query: GetSessionQuery; response: Session; childScoped: false };
  listChildren: { query: ListChildrenQuery; response: Children; childScoped: false };
  getSchedule: { query: GetScheduleQuery; response: Schedule; childScoped: true };
  getCalendar: { query: GetCalendarQuery; response: Calendar; childScoped: true };
  getLunchMenu: { query: GetLunchMenuQuery; response: LunchMenu; childScoped: true };
  getOverview: { query: GetOverviewQuery; response: Overview; childScoped: true };
}

export interface Route {
  path: string;
  schema: SchemaName;
  childScoped: boolean;
  query: readonly string[];
}

/** The route table (paths below API_BASE). */
export const ROUTES: { readonly [K in keyof Operations]: Route & { childScoped: Operations[K]["childScoped"] } } = {
  getSession: { path: "/session", schema: "Session", childScoped: false, query: [] },
  listChildren: { path: "/children", schema: "Children", childScoped: false, query: [] },
  getSchedule: { path: "/children/{childId}/schedule", schema: "Schedule", childScoped: true, query: ["week","fresh"] },
  getCalendar: { path: "/children/{childId}/calendar", schema: "Calendar", childScoped: true, query: ["start_date","end_date","fresh"] },
  getLunchMenu: { path: "/children/{childId}/lunch-menu", schema: "LunchMenu", childScoped: true, query: ["week","fresh"] },
  getOverview: { path: "/children/{childId}/overview", schema: "Overview", childScoped: true, query: ["date","fresh"] },
};

/** The answers' JSON Schemas; the client turns each into a validator once. */
export const SCHEMAS: Record<SchemaName, Record<string, unknown>> = {
  "Session": {
    "type": "object",
    "properties": {
      "schoolsoft": {
        "type": "object",
        "properties": {
          "signedIn": {
            "type": "boolean",
            "description": "The connector's SchoolSoft session is present and valid"
          },
          "loginInProgress": {
            "type": "boolean",
            "description": "The parent started a sign-in that has not finished"
          },
          "webSession": {
            "type": "boolean",
            "description": "A gated web-login session is stored (the connector does not offer one; always false today)"
          },
          "portal": {
            "type": "object",
            "properties": {
              "state": {
                "type": "string",
                "enum": [
                  "ok",
                  "backing_off",
                  "paused",
                  "probing"
                ],
                "description": "`ok`: requests to the school portal flow; `backing_off`: a short pause after the portal pushed back; `paused`: the portal pushed back repeatedly and the connector sends it nothing until `retryAt`; `probing`: the next request tests whether it answers again"
              },
              "retryAt": {
                "anyOf": [
                  {
                    "type": "string",
                    "format": "date-time"
                  },
                  {
                    "type": "null"
                  }
                ],
                "description": "When requests flow again; null while they flow or a probe decides"
              }
            },
            "required": [
              "state",
              "retryAt"
            ]
          }
        },
        "required": [
          "signedIn",
          "loginInProgress",
          "webSession",
          "portal"
        ]
      },
      "children": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "description": "Child id; use it as {childId}"
            },
            "firstName": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "firstName"
          ]
        },
        "description": "The children this connection may read, { id, firstName } as /children returns them; empty while signed out"
      },
      "scopes": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "The operations this token may call"
      },
      "routes": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "operation": {
              "type": "string"
            },
            "method": {
              "type": "string",
              "const": "GET"
            },
            "path": {
              "type": "string"
            }
          },
          "required": [
            "operation",
            "method",
            "path"
          ]
        },
        "description": "{ operation, method, path } for each route the scopes allow"
      },
      "ownerDashboard": {
        "type": "string",
        "description": "Where the parent signs in to SchoolSoft again"
      },
      "connectionExpiresAt": {
        "type": "string",
        "format": "date-time",
        "description": "When this connection's approval expires"
      }
    },
    "required": [
      "schoolsoft",
      "children",
      "scopes",
      "routes",
      "ownerDashboard",
      "connectionExpiresAt"
    ]
  },
  "Children": {
    "type": "object",
    "properties": {
      "children": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "description": "Child id; use it as {childId}"
            },
            "firstName": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "firstName"
          ]
        },
        "description": "The children in this connection, { id, firstName }"
      },
      "childInFocus": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "description": "The child reads default to, when it is in this grant; else null"
      }
    },
    "required": [
      "children",
      "childInFocus"
    ]
  },
  "Schedule": {
    "type": "object",
    "properties": {
      "year": {
        "type": "integer",
        "description": "ISO week-year: the year in which this week starts nearest today"
      },
      "week": {
        "type": "integer",
        "minimum": 1,
        "maximum": 53
      },
      "startDate": {
        "type": "string",
        "format": "date",
        "description": "Monday of the week, YYYY-MM-DD in Europe/Stockholm"
      },
      "endDate": {
        "type": "string",
        "format": "date",
        "description": "Sunday of the week, YYYY-MM-DD in Europe/Stockholm"
      },
      "child": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Child id; pass it as child_id"
          },
          "firstName": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "firstName"
        ],
        "description": "The child the result is for"
      },
      "lessons": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Stable id of this lesson occurrence"
            },
            "title": {
              "type": "string",
              "description": "Subject or lesson name"
            },
            "start": {
              "type": "string",
              "format": "date-time",
              "description": "ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00"
            },
            "end": {
              "type": "string",
              "format": "date-time",
              "description": "ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00"
            },
            "room": {
              "description": "Room; null when not given",
              "type": [
                "string",
                "null"
              ]
            },
            "group": {
              "description": "Teaching group; null when not given",
              "type": [
                "string",
                "null"
              ]
            },
            "teacher": {
              "description": "Teacher; null when not given",
              "type": [
                "string",
                "null"
              ]
            },
            "note": {
              "description": "Lesson description; null when not given",
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "title",
            "start",
            "end",
            "room",
            "group",
            "teacher",
            "note"
          ]
        }
      }
    },
    "required": [
      "year",
      "week",
      "startDate",
      "endDate",
      "child",
      "lessons"
    ]
  },
  "Calendar": {
    "type": "object",
    "properties": {
      "startDate": {
        "type": "string",
        "format": "date",
        "description": "Calendar date YYYY-MM-DD in Europe/Stockholm"
      },
      "endDate": {
        "type": "string",
        "format": "date",
        "description": "Calendar date YYYY-MM-DD in Europe/Stockholm"
      },
      "timezone": {
        "type": "string",
        "const": "Europe/Stockholm"
      },
      "child": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Child id; pass it as child_id"
          },
          "firstName": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "firstName"
        ],
        "description": "The child the result is for"
      },
      "events": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "Stable id of this calendar entry"
            },
            "kind": {
              "type": "string",
              "enum": [
                "lesson",
                "event"
              ],
              "description": "A timetable entry or a school event"
            },
            "title": {
              "type": "string"
            },
            "allDay": {
              "type": "boolean"
            },
            "start": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date",
                  "description": "Calendar date YYYY-MM-DD in Europe/Stockholm"
                },
                {
                  "type": "string",
                  "format": "date-time",
                  "description": "ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00"
                }
              ],
              "description": "Date for date-only entries"
            },
            "end": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date",
                  "description": "Calendar date YYYY-MM-DD in Europe/Stockholm"
                },
                {
                  "type": "string",
                  "format": "date-time",
                  "description": "ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00"
                }
              ],
              "description": "Date for date-only entries"
            },
            "location": {
              "description": "Room or place; null when not given",
              "type": [
                "string",
                "null"
              ]
            },
            "teacher": {
              "description": "Teacher; null when not given",
              "type": [
                "string",
                "null"
              ]
            },
            "group": {
              "description": "Teaching group; null when not given",
              "type": [
                "string",
                "null"
              ]
            },
            "category": {
              "description": "Portal category, e.g. lesson or lunch; null when not given",
              "type": [
                "string",
                "null"
              ]
            },
            "note": {
              "description": "Description; null when not given",
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "kind",
            "title",
            "allDay",
            "start",
            "end",
            "location",
            "teacher",
            "group",
            "category",
            "note"
          ]
        }
      }
    },
    "required": [
      "startDate",
      "endDate",
      "timezone",
      "child",
      "events"
    ]
  },
  "LunchMenu": {
    "type": "object",
    "properties": {
      "year": {
        "type": "integer",
        "description": "ISO week-year"
      },
      "week": {
        "type": "integer",
        "minimum": 1,
        "maximum": 53
      },
      "child": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Child id; pass it as child_id"
          },
          "firstName": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "firstName"
        ],
        "description": "The child the result is for"
      },
      "days": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "date": {
              "type": "string",
              "format": "date",
              "description": "Calendar date YYYY-MM-DD in Europe/Stockholm"
            },
            "weekday": {
              "type": "integer",
              "minimum": 1,
              "maximum": 7,
              "description": "1 = Monday … 7 = Sunday"
            },
            "dishes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "kind": {
                    "description": "Kind of meal, as the school names it; null when not given",
                    "type": [
                      "string",
                      "null"
                    ]
                  },
                  "description": {
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "description"
                ]
              }
            }
          },
          "required": [
            "date",
            "weekday",
            "dishes"
          ]
        }
      }
    },
    "required": [
      "year",
      "week",
      "child",
      "days"
    ]
  },
  "Overview": {
    "type": "object",
    "properties": {
      "child": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Child id; pass it as child_id"
          },
          "firstName": {
            "type": "string"
          },
          "schoolName": {
            "description": "School name; null when not given",
            "type": [
              "string",
              "null"
            ]
          },
          "className": {
            "description": "Class name; null when not given",
            "type": [
              "string",
              "null"
            ]
          }
        },
        "required": [
          "id",
          "firstName",
          "schoolName",
          "className"
        ],
        "description": "The child in the path"
      },
      "week": {
        "type": "object",
        "properties": {
          "year": {
            "type": "integer",
            "description": "ISO week-year"
          },
          "week": {
            "type": "integer",
            "minimum": 1,
            "maximum": 53,
            "description": "ISO week number"
          },
          "startDate": {
            "type": "string",
            "format": "date",
            "description": "Monday of the week"
          },
          "endDate": {
            "type": "string",
            "format": "date",
            "description": "Sunday of the week"
          },
          "today": {
            "type": "string",
            "format": "date",
            "description": "Today in Europe/Stockholm, the start of nextEvent's search"
          },
          "timezone": {
            "type": "string",
            "const": "Europe/Stockholm"
          }
        },
        "required": [
          "year",
          "week",
          "startDate",
          "endDate",
          "today",
          "timezone"
        ]
      },
      "schedule": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "ok"
              },
              "data": {
                "type": "object",
                "properties": {
                  "year": {
                    "type": "integer",
                    "description": "ISO week-year: the year in which this week starts nearest today"
                  },
                  "week": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 53
                  },
                  "startDate": {
                    "type": "string",
                    "format": "date",
                    "description": "Monday of the week, YYYY-MM-DD in Europe/Stockholm"
                  },
                  "endDate": {
                    "type": "string",
                    "format": "date",
                    "description": "Sunday of the week, YYYY-MM-DD in Europe/Stockholm"
                  },
                  "child": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer",
                        "description": "Child id; pass it as child_id"
                      },
                      "firstName": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "firstName"
                    ],
                    "description": "The child the result is for"
                  },
                  "lessons": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "description": "Stable id of this lesson occurrence"
                        },
                        "title": {
                          "type": "string",
                          "description": "Subject or lesson name"
                        },
                        "start": {
                          "type": "string",
                          "format": "date-time",
                          "description": "ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00"
                        },
                        "end": {
                          "type": "string",
                          "format": "date-time",
                          "description": "ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00"
                        },
                        "room": {
                          "description": "Room; null when not given",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        "group": {
                          "description": "Teaching group; null when not given",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        "teacher": {
                          "description": "Teacher; null when not given",
                          "type": [
                            "string",
                            "null"
                          ]
                        },
                        "note": {
                          "description": "Lesson description; null when not given",
                          "type": [
                            "string",
                            "null"
                          ]
                        }
                      },
                      "required": [
                        "id",
                        "title",
                        "start",
                        "end",
                        "room",
                        "group",
                        "teacher",
                        "note"
                      ]
                    }
                  }
                },
                "required": [
                  "year",
                  "week",
                  "startDate",
                  "endDate",
                  "child",
                  "lessons"
                ]
              }
            },
            "required": [
              "status",
              "data"
            ]
          },
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "not-granted"
              },
              "scope": {
                "type": "string",
                "description": "The scope this connection lacks; nothing was read"
              }
            },
            "required": [
              "status",
              "scope"
            ]
          },
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "error"
              },
              "problem": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "`urn:schoolsoft-agent:problem:<name>`; branch on this"
                  },
                  "title": {
                    "type": "string",
                    "description": "Short English title of the problem type"
                  },
                  "status": {
                    "type": "integer",
                    "description": "The HTTP status this problem is answered with"
                  },
                  "detail": {
                    "type": "string",
                    "description": "What happened, in the negotiated language"
                  },
                  "hint": {
                    "description": "What to do next, in the negotiated language",
                    "type": "string"
                  },
                  "kind": {
                    "type": "string",
                    "enum": [
                      "internal",
                      "not_authenticated",
                      "not_configured",
                      "network",
                      "not_available",
                      "input",
                      "upstream"
                    ],
                    "description": "The error kind, as the MCP tools and the CLI report it"
                  },
                  "retryable": {
                    "type": "boolean",
                    "description": "Whether repeating the same request may succeed"
                  },
                  "ownerDashboard": {
                    "description": "Where the parent signs in to SchoolSoft again (SchoolSoft-session problems)",
                    "type": "string"
                  },
                  "error": {
                    "description": "RFC 6750 error code on token problems",
                    "type": "string",
                    "enum": [
                      "invalid_token",
                      "insufficient_scope"
                    ]
                  },
                  "retryAt": {
                    "description": "When the connector sends requests to the school portal again (`portal-pushback`)",
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "title",
                  "status",
                  "detail",
                  "kind",
                  "retryable"
                ]
              }
            },
            "required": [
              "status",
              "problem"
            ]
          }
        ],
        "description": "The week's lessons: get_schedule's output"
      },
      "lunch": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "ok"
              },
              "data": {
                "type": "object",
                "properties": {
                  "year": {
                    "type": "integer",
                    "description": "ISO week-year"
                  },
                  "week": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 53
                  },
                  "child": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer",
                        "description": "Child id; pass it as child_id"
                      },
                      "firstName": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "firstName"
                    ],
                    "description": "The child the result is for"
                  },
                  "days": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "date": {
                          "type": "string",
                          "format": "date",
                          "description": "Calendar date YYYY-MM-DD in Europe/Stockholm"
                        },
                        "weekday": {
                          "type": "integer",
                          "minimum": 1,
                          "maximum": 7,
                          "description": "1 = Monday … 7 = Sunday"
                        },
                        "dishes": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "kind": {
                                "description": "Kind of meal, as the school names it; null when not given",
                                "type": [
                                  "string",
                                  "null"
                                ]
                              },
                              "description": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "kind",
                              "description"
                            ]
                          }
                        }
                      },
                      "required": [
                        "date",
                        "weekday",
                        "dishes"
                      ]
                    }
                  }
                },
                "required": [
                  "year",
                  "week",
                  "child",
                  "days"
                ]
              }
            },
            "required": [
              "status",
              "data"
            ]
          },
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "not-granted"
              },
              "scope": {
                "type": "string",
                "description": "The scope this connection lacks; nothing was read"
              }
            },
            "required": [
              "status",
              "scope"
            ]
          },
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "error"
              },
              "problem": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "`urn:schoolsoft-agent:problem:<name>`; branch on this"
                  },
                  "title": {
                    "type": "string",
                    "description": "Short English title of the problem type"
                  },
                  "status": {
                    "type": "integer",
                    "description": "The HTTP status this problem is answered with"
                  },
                  "detail": {
                    "type": "string",
                    "description": "What happened, in the negotiated language"
                  },
                  "hint": {
                    "description": "What to do next, in the negotiated language",
                    "type": "string"
                  },
                  "kind": {
                    "type": "string",
                    "enum": [
                      "internal",
                      "not_authenticated",
                      "not_configured",
                      "network",
                      "not_available",
                      "input",
                      "upstream"
                    ],
                    "description": "The error kind, as the MCP tools and the CLI report it"
                  },
                  "retryable": {
                    "type": "boolean",
                    "description": "Whether repeating the same request may succeed"
                  },
                  "ownerDashboard": {
                    "description": "Where the parent signs in to SchoolSoft again (SchoolSoft-session problems)",
                    "type": "string"
                  },
                  "error": {
                    "description": "RFC 6750 error code on token problems",
                    "type": "string",
                    "enum": [
                      "invalid_token",
                      "insufficient_scope"
                    ]
                  },
                  "retryAt": {
                    "description": "When the connector sends requests to the school portal again (`portal-pushback`)",
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "title",
                  "status",
                  "detail",
                  "kind",
                  "retryable"
                ]
              }
            },
            "required": [
              "status",
              "problem"
            ]
          }
        ],
        "description": "The week's lunch: get_lunch_menu's output"
      },
      "nextEvent": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "ok"
              },
              "data": {
                "type": "object",
                "properties": {
                  "event": {
                    "anyOf": [
                      {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string",
                            "description": "Stable id of this calendar entry"
                          },
                          "kind": {
                            "type": "string",
                            "enum": [
                              "lesson",
                              "event"
                            ],
                            "description": "A timetable entry or a school event"
                          },
                          "title": {
                            "type": "string"
                          },
                          "allDay": {
                            "type": "boolean"
                          },
                          "start": {
                            "anyOf": [
                              {
                                "type": "string",
                                "format": "date",
                                "description": "Calendar date YYYY-MM-DD in Europe/Stockholm"
                              },
                              {
                                "type": "string",
                                "format": "date-time",
                                "description": "ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00"
                              }
                            ],
                            "description": "Date for date-only entries"
                          },
                          "end": {
                            "anyOf": [
                              {
                                "type": "string",
                                "format": "date",
                                "description": "Calendar date YYYY-MM-DD in Europe/Stockholm"
                              },
                              {
                                "type": "string",
                                "format": "date-time",
                                "description": "ISO-8601 date-time with Europe/Stockholm's UTC offset, e.g. 2026-09-07T08:30:00+02:00"
                              }
                            ],
                            "description": "Date for date-only entries"
                          },
                          "location": {
                            "description": "Room or place; null when not given",
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "teacher": {
                            "description": "Teacher; null when not given",
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "group": {
                            "description": "Teaching group; null when not given",
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "category": {
                            "description": "Portal category, e.g. lesson or lunch; null when not given",
                            "type": [
                              "string",
                              "null"
                            ]
                          },
                          "note": {
                            "description": "Description; null when not given",
                            "type": [
                              "string",
                              "null"
                            ]
                          }
                        },
                        "required": [
                          "id",
                          "kind",
                          "title",
                          "allDay",
                          "start",
                          "end",
                          "location",
                          "teacher",
                          "group",
                          "category",
                          "note"
                        ]
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "The first school event (kind \"event\") that has not ended, by start; null when there is none"
                  },
                  "from": {
                    "type": "string",
                    "format": "date",
                    "description": "First day searched: today in Europe/Stockholm"
                  },
                  "until": {
                    "type": "string",
                    "format": "date",
                    "description": "Last day searched: 29 days after today"
                  }
                },
                "required": [
                  "event",
                  "from",
                  "until"
                ]
              }
            },
            "required": [
              "status",
              "data"
            ]
          },
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "not-granted"
              },
              "scope": {
                "type": "string",
                "description": "The scope this connection lacks; nothing was read"
              }
            },
            "required": [
              "status",
              "scope"
            ]
          },
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string",
                "const": "error"
              },
              "problem": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "`urn:schoolsoft-agent:problem:<name>`; branch on this"
                  },
                  "title": {
                    "type": "string",
                    "description": "Short English title of the problem type"
                  },
                  "status": {
                    "type": "integer",
                    "description": "The HTTP status this problem is answered with"
                  },
                  "detail": {
                    "type": "string",
                    "description": "What happened, in the negotiated language"
                  },
                  "hint": {
                    "description": "What to do next, in the negotiated language",
                    "type": "string"
                  },
                  "kind": {
                    "type": "string",
                    "enum": [
                      "internal",
                      "not_authenticated",
                      "not_configured",
                      "network",
                      "not_available",
                      "input",
                      "upstream"
                    ],
                    "description": "The error kind, as the MCP tools and the CLI report it"
                  },
                  "retryable": {
                    "type": "boolean",
                    "description": "Whether repeating the same request may succeed"
                  },
                  "ownerDashboard": {
                    "description": "Where the parent signs in to SchoolSoft again (SchoolSoft-session problems)",
                    "type": "string"
                  },
                  "error": {
                    "description": "RFC 6750 error code on token problems",
                    "type": "string",
                    "enum": [
                      "invalid_token",
                      "insufficient_scope"
                    ]
                  },
                  "retryAt": {
                    "description": "When the connector sends requests to the school portal again (`portal-pushback`)",
                    "type": "string"
                  }
                },
                "required": [
                  "type",
                  "title",
                  "status",
                  "detail",
                  "kind",
                  "retryable"
                ]
              }
            },
            "required": [
              "status",
              "problem"
            ]
          }
        ],
        "description": "The next school event from today, within 30 days (get_calendar)"
      }
    },
    "required": [
      "child",
      "week",
      "schedule",
      "lunch",
      "nextEvent"
    ]
  },
  "Problem": {
    "type": "object",
    "properties": {
      "type": {
        "type": "string",
        "description": "`urn:schoolsoft-agent:problem:<name>`; branch on this"
      },
      "title": {
        "type": "string",
        "description": "Short English title of the problem type"
      },
      "status": {
        "type": "integer",
        "description": "The HTTP status this problem is answered with"
      },
      "detail": {
        "type": "string",
        "description": "What happened, in the negotiated language"
      },
      "hint": {
        "description": "What to do next, in the negotiated language",
        "type": "string"
      },
      "kind": {
        "type": "string",
        "enum": [
          "internal",
          "not_authenticated",
          "not_configured",
          "network",
          "not_available",
          "input",
          "upstream"
        ],
        "description": "The error kind, as the MCP tools and the CLI report it"
      },
      "retryable": {
        "type": "boolean",
        "description": "Whether repeating the same request may succeed"
      },
      "ownerDashboard": {
        "description": "Where the parent signs in to SchoolSoft again (SchoolSoft-session problems)",
        "type": "string"
      },
      "error": {
        "description": "RFC 6750 error code on token problems",
        "type": "string",
        "enum": [
          "invalid_token",
          "insufficient_scope"
        ]
      },
      "retryAt": {
        "description": "When the connector sends requests to the school portal again (`portal-pushback`)",
        "type": "string"
      }
    },
    "required": [
      "type",
      "title",
      "status",
      "detail",
      "kind",
      "retryable"
    ]
  }
};
